.PHONY: all
all: selftest runtest

selftest: extest.hpp
	$(CXX) -o selftest -static-libgcc -static extest.cpp -DUNITTEST -DEX_SELFTEST -std=c++14 -g $(CXXFLAGS) $(LDFLAGS)

.PHONY: runtest
runtest:
	./selftest
